services:
  psigest:
    image: ${DOCKER_REGISTRY-}psigest
    build:
      context: .
      dockerfile: Psigest/Dockerfile
  database:
    container_name: Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=Password@123 
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
